accessID: ""
accessKey: ""
account: ""
affinity: {}
debug: false
enableRBAC: true
etcdDiscoveryToken: ""
imagePullPolicy: Always
imageRepository: logicmonitor/collectorset-controller
imageTag: v2
nodeSelector: {}
priorityClassName: ""
proxyPass: ""
proxyURL: ""
proxyUser: ""
tolerations: []
