accessID: ""
accessKey: ""
account: ""
affinity: {}
clusterGroupID: 0
clusterName: ""
collector:
  collectorVersion: 0
  escalationChainID: 0
  groupID: 0
  imagePullPolicy: Always
  imageRepository: logicmonitor/collector
  imageTag: latest
  priorityClassName: ""
  proxyPass: ""
  proxyURL: ""
  proxyUser: ""
  replicas: 1
  secretName: collector
  size: ""
  tolerations: []
  useEA: false
debug: false
deleteDevices: true
disableAlerting: false
enableRBAC: true
etcdDiscoveryToken: ""
imagePullPolicy: Always
imageRepository: logicmonitor/argus
imageTag: v4
nodeSelector: {}
priorityClassName: ""
proxyPass: ""
proxyURL: ""
proxyUser: ""
tolerations: []
