fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: logicmonitor/lm-logs-k8s-fluentd
  tag: 0.0.12
imagePullSecrets: []
nameOverride: ""
resources:
  limits:
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 200Mi
tolerations:
- operator: Exists
